# Generated by Django 4.0 on 2021-12-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=9)),
                ('facebook', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('A', 'Zajęty'), ('B', 'Wolny')], default='B', max_length=1)),
                ('skills', models.CharField(choices=[('A', 'Żółtodziób'), ('B', 'Niemiecki serwisant'), ('C', 'Polski serwisant'), ('D', 'Pro'), ('E', 'Leet'), ('F', 'Forest')], default='A', max_length=1)),
                ('shipment', models.CharField(choices=[('A', 'Nie'), ('B', 'Tak')], default='B', max_length=1)),
            ],
        ),
    ]
