# Generated by Django 4.0 on 2021-12-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
